export const TextAboutArr = [
  [
    `Stargaze the amazing night skies, hike to the Phoenix Park waterfall or sit on the deck and take in the view. This is a unique wilderness experience where you can see almost anything that you would backpacking, but in the comfort of a yurt.`,
    `FOR LARGER GROUPS - Now you can rent both yurts for up to 8 people. There is a trail through the wooded portion between the yurts and then a flat meadow so it's an easy 1/4 to 1/3 mile walk with basically no elevation difference between them. Both yurts are totally private from each other yet close enough that a large group can book both properties together. This yurt is accessed on a different road so you should never see the guests from the other yurt... unless you want to.

VERY IMPORTANT -we have had lots of monsoon summer rains and the last mile and a half is an unmaintained forest service road that is very rough and requires a serious 4WD vehicle with low range option and high clearance with good tires (like a truck or serious SUV or off road UTV or side by side). Hint- if your vehicle has a small donut spare tire it is NOT what you need to access the property. The forest service will fix the road at some point, but they have their plate full because of all the rain. Read our reviews to see what people say about the road and please understand that you can't have a real backcountry experience like this if any city vehicle can make it to the property! Buy, borrow, rent but get a 4WD.`,
    `PLEASE, YOU MUST ARRIVE DURING DAYLIGHT HOURS! High-clearance 4WD with good tires is REQUIRED to access the property! The yurt is not visible from the road, it is secluded and in the trees so arriving while it is still light is important.`,
    "Another reminder that true high-clearance 4WD with low range, good tires and full size spare is REQUIRED! The road is very rough from summer rains.",
  ],
  [
    `Private mountain getaway with huge views on 10 wooded acres! The property is nestled among mature timber, with a creek running through the backyard. Most days, you'll get to see moose :) The main house is 3700+ sq ft with 3 bedrooms, a loft, and 3.5 bathrooms; the detached garage is heated with 2 separate bunk-rooms. FAST Wifi (Starlink), hot tub, covered deck & patio, pool table, sunrise over Pike's Peak, and views of the Milky Way at night :)`,
    `Search "Mangy Moose Fairplay, CO" on Youtube for a video walk-through

  The main house has 3 bedrooms 3.5 baths and a loft with an office, and plenty of room for a Queen sized air-mattress (provided).
  
  The garage is HEATED and there are 2 additional bedrooms - no bathroom in the garage - so we call it the bunk room. There's a large room with 3 Queen sized beds, USB charging nightstands, and a roku TV. Wifi does extend to the garage! The smaller bedroom has a Full sized bed and a twin bed.
  
  We have 2 AWD vehicles with snow tires for rent on Turo. If you're interested- reach out ASAP for availability.
  2023 Yukon Denali Ultimate (seats 7)
  2022 Kia Telluride SX (seats 7)`,
    `Full access to the entire home and garage.`,
    `Must have AWD vehicle to access the home Nov-April, no refunds given if you get stuck in the snow. Our driveway is plowed if more than 6" accumulate overnight. If snow starts later in the day, you will not be plowed until the following day. It's $100 additional for an "emergency plow".`,
  ],
  [`This modern palace is truly a masterpiece in architecture, unparalleled opulence, mountain/resort views, and elite entertainment. Nothing was spared in this 12,000 square-foot statement in modern luxury and design. Indoor pool with infinity hot tub; upper patio mountain-view hot tub overlooking a full panorama of Breckenridge and 10-mile range; private theater; 5 luxury en-suites with mountain views; 7 bathrooms; candy dispensers; air-hockey; pin-ball; arcade machine; and operable glass walls.`,`The estate greets with a heated driveway in the winter and a mind-blowing suspended entry canopy. Walk the silver slate past a glass fireplace to the double 14' glass doors. You'll feel like royalty. The main living/entertainment area alone could fit most other luxury homes in its' footprint. You will feel as though you have an entire 4-Seasons lounge to yourself. Modern glass-wall fireplace, designer finishes and fixtures everywhere you look and touch, a sprawling chef's kitchen, enormous lounge/booth, and a fully operational glass rear wall that opens to the house-width balcony and outdoor seating. Heated two-car garage, massive laundry/entry/jacket storage and an elegant entry powder bath flank the main floor...as does the first two suites. A north side private suite presents full mountain views, walk-in closet, and magazine-worthy private bath with mountain-facing soaking tub. The south wing of the main floor is a young-persons paradise and nearly a home unto its own: A private living room and lounge area allow a generation to pick their favorite movie and hang in their own space. A game room or extra office wrap around the corner. Full south-facing glass attach all this to the bunk room with 4 full bunks and an expansive private bath.`,``]
];
